CREATE TABLE IF NOT EXISTS CURSO (
    ID          INTEGER PRIMARY KEY     AUTOINCREMENT,
    NOMBRE      VARCHAR(4)          NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPO (
    ID          INTEGER PRIMARY KEY     AUTOINCREMENT,
    NOMBRE      VARCHAR(50)         NOT NULL,
    ID_CURSO    INTEGER,
    FOREIGN KEY (ID_CURSO)  REFERENCES CURSO(ID)
);

CREATE TABLE IF NOT EXISTS ALUMNO (
    ID          INTEGER PRIMARY KEY     AUTOINCREMENT,
    NOMBRE      VARCHAR(20)         NOT NULL,
    APELLIDOS   VARCHAR(50)         NOT NULL,
    EMAIL       VARCHAR(50)         NOT NULL,
    TELEFONO    VARCHAR(9)          NOT NULL,
    ID_GRUPO    INTEGER,
    FOREIGN KEY (ID_GRUPO)  REFERENCES GRUPO(ID)           
);

INSERT INTO CURSO (NOMBRE) VALUES ("ASIR");
INSERT INTO CURSO (NOMBRE) VALUES ("DAM");
INSERT INTO CURSO (NOMBRE) VALUES ("DAW");